### ISSUE TITLE
Síntesis calidad de gestión de proyecto

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-FedericoVictorianoSierra#1]

**Comment by FedericoVictorianoSierra** [comment]
[SINTESIS SOBRE LA GESTIÓN DE PROYECTOS DE SOFTWARE (FEDERICO VICTORIANO SIERRA).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-FedericoVictorianoSierra/files/12705442/SINTESIS.SOBRE.LA.GESTION.DE.PROYECTOS.DE.SOFTWARE.FEDERICO.VICTORIANO.SIERRA.pdf)

**Comment by Gregorio012** [comment]
Calf: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
